---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: development
spec:
  encryptedData:
    database-password: AgBT5rxA9GsAfCL1hMsT0kq2NZ+pjNkJTKywfa5lZMmleh2ZfWiJRhbd2BuNUhuG6xEJau/QyFxtypuBjnt+2YPSge74EgU9cDHkkvPDfPcQnHhJ74kNz9ONoAfsbowD1vBQW4PqylHEE4xU1abSlEzqPwnrlR24b2pY1lHtn28OigGj5lfqflEmHNNXqT8bTQ4M4PTmcj6XFnmiyO7MOV8ulbBkCFwABVHMYHU5ri2VScwiy29ynTx8H2mCDvBu9cg1oseFX4ix8c9tctGRLsQlZJEglXh8HAPlY0abRGDL1hv45P5wudT6Ek0DWOmW/aaMjCJAoRKD82WZ8eCMxAq9zKe/7Jkf1+Oy2OLqW0DLR9zou4Yk6NHWLIv60m2wLTu/CMTXL/u47kVd6bbgCDzRtz+PKxrnZUwz89ANo/cQvg/fAbvAavSCfelOJvYpavctyzCGsHwauGmog+vpUmpxi4YdqH8LpynKpE/05i8rjPRNqRcX9+wiWtU45C4zjO0qzEFzEQMSJ7SRuVsc+/QVnEpiH0TD6S2xc7VJjWoFf+Nk6ftAavDbkyLxMBTnXApagOk51QZePD8Haj6acfBnhU0X5Ii64yiLvahUhcqHPJNZHNPmvjeEliL+Ih67HLAaEHV9x2z2XMhFRykolhRJv8RMFL/FdskKEMGWMAwnZotAbAgsCKmuuNjbh+ncmbESJc75CRjDCSeZOuiVUylrFVIiN+fHnoo=
    database-user: AgCgieFLKWQZ6FZPOBD2wwct5hAGUZfdsOKLLaV9fuadb9gBRK6WBm/yiVVXYwXe78645Pu2bJjCvB86sUoOW2/qGnvCx2c5aqWIm2wKd+5BEZnYeH2VlF5eBKItu5Q8uPtri58tRFF0KbELDQsLtJ3Vy4m8zrIQgdlqiWEKYGUYU5wy6ewsauqns6KxLdtTMH4V94oOMopTzUornfJRlXGoxBFn85zYo8LwjlnhV0yIbmbDhSFzAeI6nGa/F6nxdHh5fqdBuHgsZBphL7d9x28MRWFQLhm9hT/IK4JGc9PFTGDGYAzAZF52qcxroXvYlUCr2TV2/lrsmeQH2lm7/ypWvs1tsyIluH159m/4Tavq/ceXCP/egmk++749VZNOwCIFI3TGrCzrYcuDHKq8xiM+PknUDgO6HfQCJJruhQRxKSTPcITGOyKHc5lerS08S6zzDkbeT+ijqG34tcikijewbjIBOjLQIvN7HWYQu3IRtYCFfrZlmr88Dzhjon8RREIGcb/cHW9wBCrp6fd7IqcR2/PVSpT4HD0T8hSWyEdWXXTFB+XMoFijRL8f9EWEqckduPLSQurH08A+cAm/+wbHAxzRejoPiGKFN4eBExyudsUzFHhxvn2wPRt2H0Z56sNctkkzxrqEkIY8/xzIs+cEoYlieUkvBMGCh6FxPBBEMcDAfGoixYgW7Zcn4uIeefYHdPLK8jlBIg==
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: development
