---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: production
spec:
  encryptedData:
    database-password: AgB7JVhWB2qx3w7mzXT549GTen1j9m3HBr2iumXVfcN2RVnKbmy+fqCORB37rYj2NtO2ekIrCVM+SI5d8s9Y9PC3xNYjhjFIl/mZTQJtO5wlY9YlGlqfDPfRTitsVAwan5u9uIky9dtEExXRBLpZhWZxhtncs2Y4voNbTgXkG92BwNkmY5ujkz8jJ/USI6EXfWq64IyP878tkW7qbpkgo8l9uQe9mf979TMEvJsDKxyodk7E3zKwGgKL8WUKedq+H9sa81gqY23xqGXcPaqEDQiy442FurfQQIbg7X72HO/oxV2w3O47bqPwpsYeCQuhucJChVyMxcK4qc38DydGEdT8WOzFJpPnfi6H5Ykkfym5zNYcndEAGgHLSeiJl7vbrkdRHRoV73zkFZAYSkBGUT9AJKGPDbukrbIC9vjiaYKzhh5jSjMipBSnP/b+X4GFLoEwLruE9iTEThQMkVgpNSb1uXuE9NUNCmNvSMXgliu2tvTWUzGzYsFpoeSopNKFhtsfa5KATGykAsCqBFkt89J8IifrY9FlGsXlI0rNKlOqFV2LjlMvFHt3szTopjF+Pud21T1MeFslhejkurZa/ACRObyfyPgnYSlNI3DV+c5mrcGlxseMaynEnu0YWxZLRiv6+D07zGL1GAPaM4hXzI+6MnYZawy/Ro450PyToXfKzsjT+tmJ9YkgaxGf1VNJvpRRcgyFxRLQRC5swoI=
    database-user: AgAxEGZFxEGW381p9hHREwr7CYv76occot/yGUTMPQs92pbDAcHMcZogq+z3RN54rqrSPhcWM8WWb87EUFOHU2ZLBaj8tAqOkMjhlopw4wSnOWTUFDPceziRtYvbxWcstxyZqRrKwpMNDBZvm9tgyqrT5/Z8mfPuMhQRj4tEMpGGkAvvlDMtYVsOXAe9ldA3pcspFZ3toLCsO6P+uhLUV/t18//dheOkGAzQcAmHyKsr+uOqfiHVAkXdofqlmQbC8rjHAu7wy0cJNfLp1N954B6XSMZAFmcCgzMtJTLxpqCVeStV2LpfE7BK3nxRBZAqzXJ9fbn7ZEm8NjWVYNJfEZlk93uiDulInCPT4SkvJQTuCy9seUm5DGmEP9yBkJmpdn5KtUh5H3QPfHIsV3zlC6CqAqnJMEjxUQglj4uzvdRiRGCvbDiBu+K0IMTdw2t/sYIPf8oGUct/JNA5zkw2KRuGUjeZ1bSQC4PIrPQPEjrcS1gzhWwMkTtKkYKNv5yG5UlsFuKa4y+epgRJ8mcbc93yPk5D0XAIYlzL3CdRQneRcz2kyGeZ3FP+slTexA08iNQRxmnpIIVwpdtIGxjJiiMcy4n4yzR9An9i++yCJtmG0I9vt+Y3j/+H4yl0Pa/ATPX0wBKphSz4yDfdLIXBLMqZVk/LgA6rdAIn5nYouQ1AY824wJV0ZycW+JoZ06Nv71dh9X9S
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: production
