---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: production
spec:
  encryptedData:
    database-password: AgBVnvFlg1eKCD8UJ79UXNEYOw7DEaNfEBJTCpcDaeT/H/HcBA7IHLayCbmBI+8vBBNrrVTm2TNmph8PFyvUgdAn508I5paiAWwCe4YIeZ0GCrzaJkHb684hOQQ+24tdMDlsMPoP7PgUZjTlpQm7Fg/yKCakOF6sg9a18z/ta1V4fcQqTO4AAbj7ZONsO+ASoWCJC+6zU2U71De4ThbBEVHPX4o301sBAsXnUrMCbwIEWHH3Khy2HmM4GAz3KAXX39FGND+vVS/+RqrVJye3GOFeR2I/myNk40Kvv+cHLcEXYCzMtxvUKLO78WAFqMvFJPyq4trQGDJNDeT4/g8kdPtOuw4YdVvI1cMO1mtYfxB1zPRgHh2/DRo3JynSi7a5D2zZZPVDo2CMQUPfbc+KDWsDev1MtqRcMz32qHlFRc4TaARjTD88Rl4rZKSZAsy8qD56pFx8d+SlohmAMG2P60FUeUXW8VM5ylDth/H2yGljv51uhyy65zgEC8FIEOocg9h0sJt9mhBeRGWe+NCfIEX4DZE9LFopGFq/2doF4+CKTrVlVI7l/mKA25inMp1pJexfCmCAua7cxQ6ALacJjUf1ctMq9C1j41AeXMQocA2LdnBJjFDeYOaTImB+JnzoMy7IQh8kcyhpkwxCv44/anq+XZE4TpZ1DGTTFIVkyFCTn/hLKjY1wbjthR9Xan/jt57FUgwolzs/Mg3a1ak=
    database-user: AgC8rC53si+jsLfghz6gtOeMRvWwU4IeBhIjomm3j4kMb+pdmNS/S/RoSK2VCHGSQk1V64gxdBAuysHhpL3Aj3Rjmlyktd+ro99DORdZsH08JGIQ6or6+p7TVamqhCpjs841cPDnTzjjsQkqBb9kalQFPIZAU9k5VzTOWo/ZOPh9FVuX9OmTn4t+YGCUbSM9fBG+aACL0Xg7YrrXNDyh3fmyjQOg0q1cXlm2a4GkkfVSUICAQf1gY8Bv2gquchgybBUr4gt1dd53USxzcYObx3oU/AmUDqfc3nrV00I7Ae1Z5b6e1qTt1EvtN9ol/bFqpeNU/fkpZudoObQHwGPGatMq5M93hrGbo1WlraIPS0TnkgIdjYwkad8KygO4NxHgptN7QENkrD5tTeV6muC4Te7kXllWAnoM+/XLatFYO1IeGD+HV1c3B8P4lgeYPobTE635k6V+SQqvVPMHTFBfdRw57Vn0TqcXnKSIHTmxRiR+6RKFEGdQHtUW9ODnts/pTHfhyYjY43DvXpKjMVjWNt8k8gKezbVqNG6XvR3hm2eFDfV679CLLzSKHtE0Lu4TgYGDGskcxeBLG+S/siUL3lSDVrfovJIepBK2Offmq/1po2zQwAjLxJ4kI22H6RNRcrBWDPo9mG4YqBBLLd8pz8kPedJvx1Z/bi3YqTKUzyEGgExnvelgn3UxVzejaTIKdWN+NjUo
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: production
