---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: production
spec:
  encryptedData:
    database-password: AgDVsV62WJRaY+MhE2Rb4lff1bee741te2sTY52ioGejmkA+DK1l4vHEzgB1rsIP9bfwZwLAjnwXQpYeLR9R09oOuOdcTwSdeZWjnQkd0YyJ8+Lm3BfZro9YK+hNSSH+IgUHbuY3EkrR8qsMFJU00IFIQdbbcuSEEU73V3tT21Yx6WBJ+PuKwMhLFOewt+tBLrj5KYLK1fJzPWlxMHlpaSWyEnLiJ6j4R333pn5ZoTZEgMwzsBifnqDXFMrg7+ijn9zNAU/3arXtHpPCrIyMaBCzBlURoWgOEYxlAHm/hz+Kr7Z1/SPQYaRe7KxXYRKFe2cS1+D1VhnlIlIq+JVju4/bXtGrDFomTxvrDAfXwLBRyUV8pXdBV2QO0pxLA8VUKtjyT+XUbwPVN45wtrf3Xc9/0VcVBdMeCKImpkirY//8YrhFO4PTWM+bFiwkMkSYYUeIWYn+J2XNY1VzmpQ0uyE7Ojs+6FVxHv4B0S6weF6y+vwPHqyeNBMkGj1x5LOLp7iqCdCyXTwbIM7R5raDT8p23OR9MzxbiDFVdXH1VmM6BS/xl2ORR8UifMfbwFcGvt/eReMP3EQAmrFw1eNE36OgaViJiFeq8RGcZlpG3wjYC7rnU22cvaxuuydqV4Jav9MykJlCLmDv9YbaqZtwzMv7tCu2/q+bwKeMASs+G1xsaQkRPI+3zMW/oxNIMngvN71j9diuA7J/tOREFa8=
    database-user: AgBHjz4+USt+rjM+ajLOZEUVj8V03WFbBtmLZYpS6T/1sGrpmiCtPV0pQvryCAeGX+yIQahGzeJu0eCXDAVwXvKvdzJtXXWPT0EnhoAcMufhfWOPYYyY9OikpTkSkkTKfKSY5R2mDd3S6wT2hLMcUtymNJnfQtx5UORX1FTBc5CtaI4eNf0rrjqCFpZmq1JECGXEAhkJf2GyQOeu79QXqmkXNnFmyt0YcLK5jlhsk7c74xUPca4zXyTYAMUIC0uX15Fdh+WeImYMN+zQAvh3RHkQQ+Vw/ESIHc5N4HqIxSsjvONQNYmJaL+WggJoJ4Rq+UpbXjwyvPvp2nPauJ5gugfsqWnCq87z+yCCTDHnSzuySrD/U9YzEBjHej3FWLZjOpaEzkQICoM3N2ZgVIEOL+QAD+IAqGKlVSP3Y2oRaWFSzcncLZvB/PNVh4apyHCVImKLzn2UcaRK+QMREY+nIasdpqVmVkcQasCGmTcdHhOgVDzu/CY8qq+9iEasIDdsAJcM5HrmwQJWsf+BGBQfDDvikhbC/cv4hVwyWmknCy0ov9/gQmG3C04YKnT9RERSlLedG569gcY5oOYj4sXUihLa8hPIGytqS5e8AHuV64xWlicaiPKPKi17SUHRksdPibMPrKipBYYMz6gTT1U/RUs49ZB4RFtN5H8QmAtAuS85Qjz6c1teDaJOMyrp8WP5T4kB19YL
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: production
