apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopub-test
  annotations:
    codefresh.io/product: octopub
spec:
  project: default
  source:
    repoURL: https://github.com/ATGardner/octopub.git
    targetRevision: HEAD
    path: codefresh/kustomize/envs/Test
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    syncOptions:
    - Validate=false
    - CreateNamespace=true