---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: production
spec:
  encryptedData:
    database-password: AgCijl7k/YgOaAXYhKVGotUHc3yiq6wOGvL5PngxzTXGvOxx48kA5AsM5OUGT6Q7WZr3I5m2Xnbi2HNxDr39mtQJ7j3u+L8rp3jxeZXr6Ff0gurI0o6lqxaSjFp3eItd0/tqgoLTqvuni1zA1wanMEVp9WRYbSN10eeGUI8l9AWoa9BR5GYw/ApANxe7MksG4JPOAfAXqDAGnc6hpPllz+qDPDC6HniIpbT/67otJrQTuabvaEeR4SBWtuWpn67pb6eIeBrEON1rVai4L2F3eBl9nwSRXU5J+LdiOXxyMZjPCYC7Gcy60btaUkeRl4uLeotvh3tm5RJeJyM8kNHRo05bWIoKq/YCaICnaQpCp/RfBCdyeZOetib9isWVl6PxwAb+KIxcmU7m28GqN3jFF40u0YQ2tcrtcQ0bN60/uKiOsoGHWzQh0mMdj2CnEN0WEUcRgsD8xCxyXXhziIpeB+aDk+xHsNsHzXZowXStEdQ3IPOCTX9wcmlJjOmy+to9AWpkFCLWx4K63c5Py3YNJmcO8bi10w3FouYm19dtrlzd/XFy8Os2X/cWjbqpFfetP3Vyu1mnS80mTWXdd4A7oc+ygXV8/IV93qZsH+vbWfjoV5oK2/pYISu+BO3ovNNUvui0mjtASRZUdFkGKt5ELWWjRrUlrIOeKt1Z/XpK3lspMbhqpD/DsHLNEt6u55wqRvpJIXOkkhCKk6mJZkAYawYUCo0wGGQRPb0=
    database-user: AgDQlwJqteHSztaK11aVLFVy8QaZewGfEO8Zr1bfvP5+4xN1JuVWm9jKxh2uNvQ4xFK4hMdEOTB5Q21huhzwi2uzJkzBe2uT2upbZ74U8hNBd3rXYAPDypQdgPP2Ggz6t8C/Wcz4r0WT2DhFU3TdpMbziZv5rZjLj0dofmU3AiuuaLLnRb8JpqC4D+0ACeFC2PLT6Qog6aZiCBczvGRyWs8NIZ3BXsBym/bAE9Uq6TWraRe8LCYHSXR20qeaGQyl+QjCaIUVZvn5qzrm7ZTR9xjjZLPT6lEDx2pzf1l66ba1K9V98vBocE8f19RHPI4/mHzZgHBevDLr6ROL0Fhe9g1uEHKjvHtswaNBJGbVySEl348xJA0Q+o2GDZSLF4jK3BzkSs2JSt2apBsaz3NbMOFSlXoOlAFigF1GNgyVnop/LwFDcpBNypdGR0ToBYwdN00vHyS8Ap6aPAhJImwl5X2AcIE+knsfCEAyxODQA98EoBs6ypPv9GrYvX3la5fVWcVa9QnT7960Au9go9wjz73K3E8XvcTRg6VlwIxT2qvMIkg2tLNo6ueIYNOzf1yC6LqhEStC7rO6vfdc3EeGbrdse8vH8nCUpol8RYRMwndZgepynACpXg+2QkD6TFd8EWckI6SSiN0gQQSEEmWX22GTBDuWmalUw1DfZcj64vTDYsWX0Qbj91zSFhi3OX//hnh2Gyy9HBI9zg==
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: production
