apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: octopub-development
  annotations:
    codefresh.io/product: octopub
spec:
  generators:
  - list:
       elements:
       - cluster: in-cluster
         url: https://kubernetes.default.svc 
       - cluster: k3s1
         url: https://k3s1:6443
  template:
    metadata:
      name: '{{cluster}}-octopub-development'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/twerthi/octopub.git
          targetRevision: HEAD
          path: codefresh/kustomize/envs/Development
        - repoURL: https://github.com/twerthi/octopub.git
          targetRevision: HEAD
          path: codefresh/kustomize/octopub-secret/{{cluster}}/development
      destination:
        server: '{{url}}'
        namespace: development
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - Validate=false
        - CreateNamespace=true