---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: production
spec:
  encryptedData:
    database-password: AgCN/v1mhF/CnI0XWMUNa6oMRdPymqkA5qgUYvCExhiwo2cn56/Uy2VFOUXDfaq/j+PasMh9VNfFBRpTxlEJB1sAWtf9D5AMcr2pkIXi1VuuedFTX2DiJtpumOItarZF/58pFU+UBsKBBdzMEe9WE6GW+7xiLm+lgfWmudsNkBm89BoAI+ubg+HvpRPBVkdVceBSzXr1X5W7bVxwEz0NgWJ3S7iU4lRlBCYfvyUbFFHSu1s7l0SZh2jST6Y1JXLurnK4JYItmviorsBnYEnbt3KrRWH4EPNsSrWJ4B5OYmc5CB49X0F4ydl6JpJqsr4107FPG9uVu9RJTtI1iC0fxTC2NIFw6Be7CWMEjpg9xykulW5VXgrab4FPtvomk25CRz8tbEZK7AOvsXuHRZTpAnB2sC2vE96bKc3cdTjHoHRBT3TV80Q0/1f/CJyTdLgTuFgRXviY1hPso/4pDnlZh6LlzIoMlz+LmZtflci21DAOVAQylG9dzvs4KSkBU6QLlf314arDdRgDUuCOxx1Vzhn92XECn7I8mAVq6S3wl8FpxRTlcpS48jzs70JKHaAPJwNyA1U8mB77jttvbuw+vjOYKZCyNkHKRhnhPOBlUEtD6/vatX5Zk/4lmhIIpBNaxBFaQ+EtqsYg3ZYYIs0Wg9wsORNDPWi4FaN0WSzY6AcdI5kuHoNnlCNq92MA7nMED8B0G4fwZJxV39rihHw=
    database-user: AgCp0Ly+x+VGRjZ8Msk7KpV6Woi78gmfxby9y8Tfhz9+BW9Q+u0L8ljcJbWFEI290FrUAW3gMMqs81o7seNN3ZUVAqAlLQJPwHm4Rk4SQCeVGSu+18cmfmjWYTBpl22NwvgfmMpHeHQCUFimTeYU/QafRZnVg07Rjlp7hfxkNrxYCxq9q3l5W4dFD4ZSqO2mEqL6wkuUDDGhEeixwwjuc0WL3AzRGoOcwRaZSkTFE77dWV8S2IHSoTpy0HjCfZxHrrUEqfJ55ehnQdo9RxCOuitKApvX15Yc4uvOAWpBjLygSxVwRLQmAHuDwdcneM4AIMIZr73Curwb6anhvaifN6/Hncp3OzOYOMHTVJXJ1Y9LzyO1avSEoAOwaI6YVpAumKLx82qmWFPDR0/E2LjRzWJCoG3+1Wwm9osaY8m95LdYGQ6yG5fF5TBC58I4AZf8Nzm3Lcp/NWIOWiuvToF2g3CtigacYVbbE6FjWghEyj23bFq6kCEOsws44EiUTik/zrzI6R4hAFpJLbN6foCBUfkG/jK5kCejtmHqapRzFlFNcsL0UmWgcmeBbBNFF2LQAPrGkWTC7U4uiZKZprrB5QcFzy1mGFEgCgtDluIvH/hyOVOm7XnkhPk0O9qUds3wpzTxbtQQVIAoXdGFCd0hebN0m9RSDE7NaZriGEVJDdGQx1QgjuzLlWBD3Pa5r/J3Lq+YnolN
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: production
