---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: production
spec:
  encryptedData:
    database-password: AgADd1n7Pv8hgVIJt6jQ5JiB6UmkStyxPAY7u6dtOfp9xiTMMO49tlZqGdXtijqhWULQaR6Y5z7J9imKV2EyUFY1AqWSfUuFHasiWPtVTj6Ls2aV0Zi3Siin63I/rSnEU21fcVZ9pk/QufWa4wEB1diEFR+h7iFkz3FeqhRPIS6PED9PJ0KEtC9P+guSXEchMaLYG+ftXa0JdgJLTnZaIz3+J6c890hXIGxhVJKAPpGcbL1tVZL82eCg3dvEESWXyddQ4lLDqExl3evmEamT2RKjzB2NuTNs0SM4ccZYCdCWtRc5w0RIuvoedBjC3hNQ3+mrRkPIoFJ06JcWlBzydPYbe7SPpRrXhr2GpH2N12ZdrVxoNS2f95Z04v5Vd1RTNCUhce91VWL1xfr+ZyuQawPvZNz5IoeObYyZYgobXC3MJF8bl+aXIh1u4HWBVbGO9LD5YBQnIj3tfm7tazOGPlTJjrcmKwlIj341HSIEmjhicb+/oBeClu7SSZq72vuiC/7SbXEyG+1x25R17uvhdGgHY+7w2F8k+nFcWBPv4QSWzC39a9at2MQG297hofGlehKV4q/6vPEZzhoDBsX1nvPR30tTKmCt0pJibxbtyEhTZIf0M57i9EcH9yG7XF5VKvyHKAJXMCGLVKkDqDk0HcDkASDs8Oa1mgHzk3L6fIexAkUvQkFjwhqD2YyLuaaVi7p+KqwblT0wtnxprUQ=
    database-user: AgB7+0XxatBLyUaiVLe5Ohn91NmHD6ACxwImkqhBCM3+5QH6CZygB6VVUljw4f3iag0Ji+i/DW6v0yd7Xo3iF0fqaqHMdI1QXRwtWx/4UmOClK1g9KXs+K3ljsZpIJ9EyYa7PKIWPWKbMRELC/TYmtKOl3qrDg4O6VjyImxaLgGnWScDlOFOE7/CXv3UdF+g+M6uaPYGqlzH1YRL/yqyZD56YQ2T6IB2LKc6VVykQLCI9KAHGoLmXJccqn04YUdrDLZ1IvGvMIkYBFgV8sepLw6wUF0fGh6o8XQhnSXZB2ux0c+zTgPPHzjy4Tv+SME59O3j7qdZoqX985vU/qVR8GiE7fSotsqZmYOyFlAbQOim0N82Vb+bqWsCKhEEkXKBybPxvd4FMOrIyUdvLeDIQoNnZB1/whAp6bxCIg7RZzZAR5LOBr8ioY4qQcpy0b4uzF/m46ciu3dUCQDT+m3Mc0g2wE1pttG+em/+NvEnXC4QN7c4PRopY0kxF4FIaxPU0vBWqoaGYU/NmXfq+mpyvbYZe2t3aY1S1ZB7fOj/2YHoAtp+ef9GuwxNxBARes/S+K9Out3BTOf5gsvVqkdOWpYhOQw2kgSa9yt4TPSRIjkmE9fZ1pEfUvnyLBk7Dzj/yi/3RyNfJxpBKJiX9ww4WgBfkbOmncs59taB6mpPWuQxgCY4iTLyzXs9YGC9EqcxqYRlaoVT
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: production
