name: Docker Build and Push

on:
    workflow_dispatch:

jobs:
  build:
    name: Build, tag, and push audit image to Dockerhub
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Set Version
          run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

        - name: docker login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: build audit service docker jar
          run: |
            chmod +x ./mvnw
            ./mvnw --batch-mode package --file pom.xml -DskipTests -Dquarkus.profile=mysql
          shell: bash
          working-directory: java/audit-microservice
        - name: build audit service docker image
          run: |
            docker build -f Dockerfile.legacy-jar -t twerthi/octopub-audit-microservice-mysql:${{ env.PACKAGE_VERSION }} .
            docker push twerthi/octopub-audit-microservice-mysql:${{ env.PACKAGE_VERSION }}
          shell: bash
          working-directory: java/audit-microservice/src/main/docker

        - name: build product service docker image
          run: |
            ls -la
            docker build -f /Dockerfile.legacy-jar -t twerthi/octopub-products-microservice-mysql:${{ env.PACKAGE_VERSION }} .
            docker push twerthi/octopub-products-microservice-mysql:${{ env.PACKAGE_VERSION }}
          shell: bash
          working-directory: java/products-microservice/src/main/docker

        - name: build frontend docker image
          run: |
              ls -la
              ls -la java/octopub-frontend
              docker build -f Dockerfile -t twerthi/octopub-frontend:${{ env.PACKAGE_VERSION }} .
              docker push twerthi/octopub-frontend:${{ env.PACKAGE_VERSION }}
          shell: bash
          working-directory: js/frontend