name: Just build info
permissions:
  contents: write
  packages: write
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: self-hosted
    env:
      OCTOPUS_URL: ${{ secrets.OCTOPUS_SERVER_URL }} # address of Octopus Deploy instance (i.e. https://demo.octopus.app)
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }} # API key used with Octopus Deploy instance
      OCTOPUS_SPACE: ${{ secrets.OCTOPUS_SPACE }} # or you can specify a Space ID    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push build information to Octopus Deploy 🐙
        uses: OctopusDeploy/push-build-information-action@v3
        with:
          packages: |
            twerthi/octopub-audit-microservice-mysql
          version: 1.0.3
